services:
  app:
    # nazwa kontenera / serwisu
    build: . # buduj image z Dockerfile w aktualnym folderze
    image: url-monitor:latest
    container_name: url-monitor
    volumes:
      - .:/app # mount folderu lokalnego do kontenera
    env_file:
      #plik ktory ma w sobie env variables
      - .env
    environment:
      URLS: ${URLS}
      INTERVAL: ${INTERVAL}
    command: python -m flask run --host=0.0.0.0 --port=5000 --debug
    restart: always
  web:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - ./output:/usr/share/nginx/html
    restart: always
