apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: url-monitor-api
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - url-monitor
  selector:
    matchLabels:
      app: url-monitor-api
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
