apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-monitor-api
  namespace: url-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-monitor-api

  template:
    metadata:
      labels:
        app: url-monitor-api
    spec:
      containers:
        - name: api
          image: url-monitor:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          command: ["python", "src/api.py"]
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
