apiVersion: v1
kind: Service
metadata:
  name: url-monitor
  namespace: url-monitor
  labels:
    app: url-monitor-api

spec:
  selector:
    app: url-monitor-api

  ports:
    - name: metrics
      protocol: TCP
      port: 5000
      targetPort: 5000

  type: NodePort
     