apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-monitor-worker
  namespace: url-monitor

spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-monitor-worker

  template:
    metadata:
      labels:
        app: url-monitor-worker

    spec:
      containers:
        - name: worker
          image: url-monitor:latest
          imagePullPolicy: IfNotPresent    
          command: ["python", "src/worker.py"]
          envFrom:
            - secretRef:
                name: url-monitor-secret
          resources:
            requests:
              memory: "350Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

