name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        # checkout
      - uses: actions/checkout@v5
       # setup python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
       # install deps
      - run: pip install -r requirements.txt    
       # py_compile
      - run: python -m py_compile src/worker.py src/api.py
      # run tests
      - name: Run Tests
        run: python -m pytest /tests -v
       